name = "flareact-template"
type = "webpack"
account_id = "06033a87f7e1765b483ec12a725074d3"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
